crossfilter/crossfilter

package.json
src/crossfilter.js

This utilizes the `package-json-versionify` browserify transform I included in the original build overhaul PR and forgot to actually use. The overall effect of this is a reduced `crossfilter.js` and `crossfilter.min.js` build size (about 57 lines removed).
Risk of breakage to crossfilter is (or should be) 0 since the only use of package.json in crossfilter is of the version field.

Use browserify transform to only include package.json's 'version' field

---

package.json

I made a mistake in PR #48 where I excluded the `src` folder from being uploaded to npm. I should have included the files because webpack and jspm bundle the source files directly instead of using the prebuilt files. Package managers like bower should and will need to reference the built `crossfilter.js` and `crossfilter.min.js` files. My apologies for the mixup.
Here is the output I get from webpack today using crossfilter2@1.4.0-alpha.2:
```
ERROR in ./~/crossfilter2/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/crossfilter in /Users/Mark/projects/badgeup-dashboard/node_modules/crossfilter2
@ ./~/crossfilter2/index.js 1:17-45
```
Ping @esjewett

Include source files in npm package

---

package.json
src/crossfilter.js
test/crossfilter-test.js

This PR introduces the ability to use a string based shorthand when creating dimension accessors, see examples below.
* Includes test coverage
* All existing tests pass
I use this enhancement to reduce boilerplate and help crossfilter/dc.js projects maintain readability. Since this could be of use to others I figured I would suggest it upstream.
A simple property name
```js
data.dimension(function(d) { return d.type; });
```
Can now be [expressed as](#diff-651f62a9bb8f6bd367f8fe5af63791baR66):
```js
data.dimension('type');
```
Accessing an array value
```js
data.dimension(function(d) { return d.tags[0]; });
```
Can now be [expressed as](#diff-651f62a9bb8f6bd367f8fe5af63791baR68)
```js
data.dimension('tags[0]');
```
Accessing a value on an object within an array (any level/combination of …

feat: Adds string shorthand for creating dimension accessors

---

package.json

This PR reduces the size of `crossfilter.min.js` from [~31kb](https://github.com/crossfilter/crossfilter/blob/master/crossfilter.min.js) to [~17kb](https://github.com/TomNeyland/crossfilter-1/blob/bundle-optimization-artifacts/crossfilter.min.js) by enabling [uglify's compressor](https://github.com/mishoo/UglifyJS2/blob/master/README.md#compressor-options) and [mangler](https://github.com/mishoo/UglifyJS2/blob/master/README.md#mangler-options)
* Updates the uglify options
* Does not commit an updated build

Reduce minified bundle size by ~50%

---

src/crossfilter.js
test/crossfilter-test.js

Found an issue with the way empty rows and filter status were being tracked with array dimensions. IterablesEmptyRows was being overwritten every time data was added and oldIterablesIndexFilterStatus was incorrectly being used when setting new values.

Fixed array dimensions empty row tracking and filter status tracking.

---

src/crossfilter.js
test/crossfilter-test.js

Found an issue with disposing groupAll groups. Disposing a groupAll group removed all filter and data listeners that came after its own listeners.

Fixed issue with disposing groupAll groups.

---

src/crossfilter.js
test/crossfilter-test.js

When a new key was added to the group that was less than a previously added key, the groupIndex was not being rebuilt correctly.

Fixed an issue with rebuilding the groupIndex on array dimension groups.

---

src/crossfilter.js
test/crossfilter-test.js

So I went down a bit of a rabbit hole with removing data with iterable dimensions. It seems that iterable dimensions and groups were never accounted for in the removeData functions.
There were also some issues with filterFunctions after the removal of data. The length of the index was being used even though the index array is never trimmed after data had been removed. The value array is trimmed, so I replaced the references to `index.length` with `values.length`. Also, `n` (the number of records) was being used as the default upper bounds when a filterFunction was being set. This, unfortunately is not the case for iterable dimensions since the upper bound can be higher or lower than the number of records, unlike normal dimensions.
There was also a small issue with adding one value or an …

Fixed issues with removing data from iterable dimensions and groups.

---

package.json
src/crossfilter.js
test/crossfilter-test.js

This PR should fix memory leak when groups are created and disposed frequently.
Fixes #87
I haven't found any mocking/spy library in dev dependencies, so created dummy spy.
If more generic spy library is ok, we can add something like sinon. If you don't mind, I can update PR
Note that I haven't included built version of `crossfilter.js` / `crossfilter.min.js`

Crossfilter leaks memory when disposing groups, fixes #87

---

package.json

I just found this broken link for the homepage. Annoying because it is in the metadata and displays on NPM etc.

Broken link in package.json

---

src/crossfilter.js
test/crossfilter-test.js

Allow ignoring of dimension filters in crossfilter.allFiltered() (#63)

---

index.d.ts

It was void, but needs to be a `() => void`.

Correct the onChange return type

---

index.d.ts

Problem:
```
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209
75 |   }
76 |
> 77 |   export const enum EventType {
|                     ^
78 |     DATA_ADDED = 'dataAdded',
79 |     DATA_REMOVED = 'dataRemoved',
80 |     FILTERED = 'filtered',
```
Steps to reproduce:
```
yarn create react-app sampleProject --typescript
cd sampleProject
yarn add crossfilter2
add `import cf from "crossfilter2";` to App.tsx
yarn start
```
Reference:
Codesandbox link: https://codesandbox.io/s/w2y0xr1wrw
Now deployment: https://zeit.co/inanis/csb-w2y0xr1wrw/aqxbmozifj
***Important***: For some reason I could not reproduce the bug on Codesandbox, but during build phase in the Now deployment it happened and it also happens on my machine.
Relevante …

fix: typescript definition error TS1209

---

index.d.ts

Considering the following snippet : 
```javascript
interface Payment {
date: string;
quantity: number;
total: number;
tip: number;
type: string;
productIDs: String[];
}
var payments = crossfilter<Payment>([
{date: "2011-11-14T16:17:54Z", quantity: 2, total: 190, tip: 100, type: "tab", productIDs:["001"]},
{date: "2011-11-14T16:20:19Z", quantity: 2, total: 190, tip: 100, type: "tab", productIDs:["001", "005"]}
]);
interface Group {
total: number;
}
var paymentsByType = payments.dimension(d => d.type);
var paymentVolumeByType = paymentsByType.group<number,  Group>().reduce(
(p, v, nf) => {
p.total = p.total + v.total;
return p;
},
(p, v, nf) => {
p.total = p.total - v.total;
return p;
},
() => {
return {
total: 0
};
}
);
```
Without the patch, we have this TS error : 
```
[tsl] ERROR in …
```

fix #119 : Types for `reduce()` function are too restrictive

---

index.d.ts

Closes #120 
This PR adds type handling for arrays as return types for dimension selectors.

Add typing for arrays as returned dimension accessor type

---

index.d.ts

Those aren't cloned, so they can't be modified.
According to [`group.all()`'s documentation](https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-group_all) that you can't modify the returned array. This wasn't reflected in `index.d.ts`. I assumed the same would hold for [`crossfilter.all()`](https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-crossfilter_all).
This change might break some other projects that depend on this file, but I'm not sure how else to correct this.

Add readonly to some returned arrays in index.d.ts.

---

test/crossfilter-test.js

adding records while filters are active on a tag dimension results in inconsistent state
this includes 5 failing tests for #127

tests demonstrating bad results when adding records with tag dimension filtered

---

src/array.js
src/crossfilter.js

I am very surprised that going back to typed arrays, #134, breaks 17 tests.
I'd like to see this functionality restored in 1.4.8. Even if it doesn't help performance on Chrome, it is likely to help performance on other browsers.
But why does this break anything? Anyone have an idea? I keep staring at this thinking I must have made a typo.

restored typed arrays that were disabled in 70fb3dca54 / db6ff2d1f8a

---

README.md
package.json

This is to avoid potential confusion and unnecessary installs.

Remove more remaining traces of uglify

---

.github/workflows/tests.yml
.travis.yml
package-lock.json

Since Travis CI starts to reduce quotas for OSS projects (and I believe DC.js already uses GitHub Actions).
While doing that, add `package-lock.json` to make the CI run reproducible.

Migrate CI to GitHub Actions
